### ISSUE TITLE
[Request] Build Instructions, or Provide for other CUDA versions?

### ISSUE THREAD

**Issue by d8ahazard** [DeXtmL/bitsandbytes-win-prebuilt#1]
Hey there! I'm trying to create an extension for Stable Diffusion that runs Dreambooth. 

Unfortunately, the current version of SD-Webui uses the 11.3 version of the CUDA toolkit, as that's the latest version available for windows, I believe.

Point being - would it be possible to create a prebuilt version of the windows binaries that work for the 11.3 tookit?

Also, build instructions would be awesome, I could possibly help out with prebuilts then.

**Comment by DeXtmL** [comment]
Please refer to this issue: 
https://github.com/TimDettmers/bitsandbytes/issues/30#issuecomment-1257229487

If you wish to compile all other versions, the best way is to make a makefile

**Comment by eranmahalu** [comment]
Hi there, I tried to install the Dreambooth extension and got these following errors, can you please help?

"Error loading script: main.py
Traceback (most recent call last):
  File "E:\_AI_\SD\Local\stable-diffusion-webui\modules\scripts.py", line 155, in load_scripts
    exec(compiled, module.__dict__)
  File "E:\_AI_\SD\Local\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\main.py", line 3, in <module>    from dreambooth import conversion, dreambooth
  File "E:\_AI_\SD\Local\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\conversion.py", line 26, in <module>
    from dreambooth.dreambooth import get_db_models
  File "E:\_AI_\SD\Local\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 10, in <module>
    from dreambooth.train_dreambooth import main
  File "E:\_AI_\SD\Local\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 20, in <module>
    from accelerate import Accelerator
ModuleNotFoundError: No module named 'accelerate'"

Thanks so much

**Comment by wanjunling168** [comment]
> Hi there, I tried to install the Dreambooth extension and got these following errors, can you please help?
> 
> "Error loading script: main.py Traceback (most recent call last): File "E:_AI_\SD\Local\stable-diffusion-webui\modules\scripts.py", line 155, in load_scripts exec(compiled, module.**dict**) File "E:_AI_\SD\Local\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\main.py", line 3, in from dreambooth import conversion, dreambooth File "E:_AI_\SD\Local\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\conversion.py", line 26, in from dreambooth.dreambooth import get_db_models File "E:_AI_\SD\Local\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 10, in from dreambooth.train_dreambooth import main File "E:_AI_\SD\Local\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 20, in from accelerate import Accelerator ModuleNotFoundError: No module named 'accelerate'"
> 
> Thanks so much

read the error message bro, obviously you forgot to install `accelerate` @eranmahalu
